---
en:
  - Overview: overview.md
  - Guides:
    - Accepting Payments: guides/accepting_payments.md
    - Converting Payments to Fiat Currencies: guides/converting_payments_to_fiat.md
  - Reference:
    - Overview: reference/overview.md
    - Signing Requests: reference/signing_requests.md
    - Error Responses: reference/error_responses.md
    - Gateways:
      - Overview: reference/gateways/overview.md
      - Create: reference/gateways/create.md
      - Show: reference/gateways/show.md
      - Update: reference/gateways/update.md
      - Delete: reference/gateways/delete.md
    - Cashila Address Provider:
      - Overview: reference/cashila_address_provider/overview.md
      - Create: reference/cashila_address_provider/create.md
      - Show: reference/cashila_address_provider/show.md
      - Update: reference/cashila_address_provider/update.md
