---
en:
  - Introduction: introduction.md
  - Overview of Payment Processing: overview_of_payment_processing.md
  - Creating a New Gateway: creating_a_new_gateway.md
  - API:
      - Signed Request: api/signed_request.md
      - Creating Orders: api/creating_orders.md
      - Receiving Order Status Change Callback: api/receiving_order_status_change_callback.md
      - Checking Order Status Manually: api/checking_order_status_manually.md
      - Order Websocket: api/order_websocket.md
      - Order Cancellation: api/order_cancellation.md
      - Receiving Last Keychain ID for Gateway: api/receiving_last_keychain_id_for_gateway.md
  - Developer API:
      - Basic: developers_api/basic.md
      - Gateways: developers_api/gateways.md
      - Address Providers:
        - list: developers_api/addressproviders/list.markdown
        - Cashila:
          - login: developers_api/addressproviders/cashila/login.markdown
          - withdraw: developers_api/addressproviders/cashila/withdraw.markdown
          - Legal Entity:
            - create: developers_api/addressproviders/cashila/legalentity/create.markdown
            - get: developers_api/addressproviders/cashila/legalentity/get.markdown
            - update: developers_api/addressproviders/cashila/legalentity/update.markdown
          - Individual Entity:
            - create: developers_api/addressproviders/cashila/individualentity/create.markdown
            - get: developers_api/addressproviders/cashila/individualentity/get.markdown
            - update: developers_api/addressproviders/cashila/individualentity/update.markdown
